/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netflixswing.view;

/**
 *
 * @author anacvignola
 */
public class navbar extends javax.swing.JPanel {

    /**
     * Creates new form navbar
     */
    public navbar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        btnhome = new javax.swing.JLabel();
        btnseries = new javax.swing.JLabel();
        btnmovies = new javax.swing.JLabel();
        btnaddrecent = new javax.swing.JLabel();
        btnmylist = new javax.swing.JLabel();
        btnkids = new javax.swing.JLabel();
        btnsearch = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnuser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        setBackground(new java.awt.Color(38, 38, 19));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netflixswing/view/logo-netflix-256.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(3500, 946));
        jLabel1.setMinimumSize(new java.awt.Dimension(3500, 946));

        btnhome.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        btnhome.setForeground(new java.awt.Color(254, 254, 254));
        btnhome.setText("Início");

        btnseries.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnseries.setForeground(new java.awt.Color(254, 254, 254));
        btnseries.setText("Séries");

        btnmovies.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnmovies.setForeground(new java.awt.Color(254, 254, 254));
        btnmovies.setText("Filmes");

        btnaddrecent.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnaddrecent.setForeground(new java.awt.Color(254, 254, 254));
        btnaddrecent.setText("Adicionados Recentemente");

        btnmylist.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnmylist.setForeground(new java.awt.Color(254, 254, 254));
        btnmylist.setText("Minha Lista");

        btnkids.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        btnkids.setForeground(new java.awt.Color(251, 251, 251));
        btnkids.setText("INFANTIL");

        btnsearch.setForeground(new java.awt.Color(250, 253, 255));
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netflixswing/view/search-13-24.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netflixswing/view/icons8-notification-30.png"))); // NOI18N

        btnuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netflixswing/view/user.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netflixswing/view/seta_branca.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnhome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnseries)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmovies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnaddrecent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmylist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)
                .addComponent(btnsearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnkids)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(btnuser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnkids)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnhome)
                                    .addComponent(btnseries)
                                    .addComponent(btnmovies)
                                    .addComponent(btnaddrecent)
                                    .addComponent(btnmylist)
                                    .addComponent(btnsearch))
                                .addComponent(btnuser)
                                .addComponent(jLabel4)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnaddrecent;
    private javax.swing.JLabel btnhome;
    private javax.swing.JLabel btnkids;
    private javax.swing.JLabel btnmovies;
    private javax.swing.JLabel btnmylist;
    private javax.swing.JLabel btnsearch;
    private javax.swing.JLabel btnseries;
    private javax.swing.JLabel btnuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
